#!/usr/bin/env bash
SOURCED=false && [ "$0" = "$BASH_SOURCE" ] || SOURCED=true

if ! $SOURCED; then
  set -euo pipefail
  IFS=$'\n\t'
fi

# Simple config file that supports comments
# See:
#   * Bash parsing variables from config file
#     https://stackoverflow.com/questions/16571739/
function parse_config() {

  local configfile="$1"

  while IFS='= ' read lhs rhs; do
    if [[ ! $lhs =~ ^\ *# && -n $lhs ]]; then
        rhs="${rhs%%\#*}"     # Del in line right comments
        rhs="${rhs%%*( )}"    # Del trailing spaces
        rhs="${rhs%\"*}"      # Del opening string quotes
        rhs="${rhs#\"*}"      # Del closing string quotes
        declare $lhs="$rhs"
    fi
  done < "$configfile"
}

# Double checking if the Yubikey is actually removed,
# Challenge-Response won't trigger the screensaver this way.
LOCK_TIMEOUT='30'

# tested with just 1 user at the moment
username="$(who -u | awk '{print $1}' | sort | uniq)"
uid=$(id -u "$username")

# if no file authorized_yubikeys is found exit
if [ ! -f "/home/$username/.yubico/authorized_yubikeys" ]; then
  (>&2 logger "[yubikey] file /home/$username/.yubico/authorized_yubikeys "
              "not found")
  exit 1
fi

auth_keys_perm="$(stat -c '%a' "/home/$username/.yubico/authorized_yubikeys")"
if [ "$auth_keys_perm" == '600' ]; then
  (>&2 logger "[yubikey] file /home/$username/.yubico/authorized_yubikeys "
              "must have permission 600")
  exit 1
fi

# if no file authorized_yubikeys is found exit
configfile=("/home/$username/.yubico/yubikey-screensaver/" \
            "yubikey-screensaver.conf")
if [ ! -f "$configfile" ]; then
  parse_config "$configfile"
fi

# get D-bus session
source "/run/user/$uid/dbus-session"
export DBUS_SESSION_BUS_ADDRESS
export DISPLAY=':0'

# delete the lock if older than 30 minutes
[ -f "/run/user/$uid/yubikey-lock-screen" ] && \
  find "/run/user/$uid/yubikey-lock-screen" \
    -type f -empty -cmin "+$LOCK_TIMEOUT" -exec rm "{}" \; || true

screen_locked=$(/bin/su $username -c \
                  'dbus-send --print-reply \
                             --dest=com.canonical.Unity \
                             /com/canonical/Unity/Session \
                             com.canonical.Unity.Session.IsLocked | \
                      grep -q "true" && echo true || echo false' )
logger "[yubikey] screen_locked: $screen_locked"

yubicokeys=$(lsusb | grep 'Yubico' | \
                     awk -F':' '{print $1}' | \
                     sed -r 's#Bus ([0-9]+) Device ([0-9]+)#\1:\2#g' || true )
key_is_authorized=false
found_key=false

# FIXME: differentiate add from change/remove
if [ ! -z "$yubicokeys" ]; then
  for serdev in $yubicokeys; do
    serialno=$(lsusb -v -s "$serdev" | \
                  grep iSerial | awk '{ print $NF }' \
                  || true )
    key_is_authorized=$(grep  -qE "^$serialno$" \
                        "/home/$username/.yubico/authorized_yubikeys" \
                        && echo true || echo false)
    if $key_is_authorized; then
      # TODO: add key challenge (avoid USB spoofing)
      break;
    fi
  done

  if $key_is_authorized; then
    logger "[yubikey] yubiKey: ID_SERIAL_SHORT: $serialno - key authorized"
    found_key=true
  fi
else
  found_key=false
fi

# if /home/$username/.yubico/.nolock is present, set no_lock
no_lock=false
if [ -f "/home/$username/.yubico/.nolock" ]; then
  no_lock=true
fi

if ! $found_key; then
  logger "[yubikey] yubiKey removed or changed"

  if ! $screen_locked; then
    if $ask_confirmation; then
      if $no_lock, then
        dialog_response=$(
          zenity --question \
                 --title='Confirm' \
                 --cancel-label="Don't lock" \
                 --ok-label='Lock' \
                 --text='File ~/.yubico/.nolock found, confirm screen lock')
      else
        dialog_response=$(
          zenity --question \
                 --title='Confirm' \
                 --cancel-label="Don't lock" \
                 --ok-label='Lock' \
                 --text='File ~/.yubico/.nolock found, confirm screen lock')
      fi
    fi

    if [[ "$dialog_response" == 'lock' ]], then
      no_lock=false
    else
      no_lock=true
    fi

    if ! $no_lock; then
      logger "[yubikey] locking screen"

      # Running the screensaver lock command
      /bin/su $username \
        -c "/usr/bin/gnome-screensaver-command --lock"

      touch "/run/user/$uid/yubikey-lock-screen"
    fi

  else
    logger "[yubikey] screen already locked, doing nothing"
  fi

else
  logger "[yubikey] yubiKey found, unlocking screensaver if found"

  # does not work with Unity's lock screen
  # Running the screensaver unlock command
  # /bin/su $username \
  #  -c "/usr/bin/gnome-screensaver-command --deactivate"

  if [ -f "/run/user/$uid/yubikey-lock-screen" ]; then
    logger "[yubikey] screen was locked with yubikey"

    if $screen_locked; then
      # unlocks all sessions, ok if there is only one user
      logger "[yubikey] unlocking screen"
      loginctl unlock-sessions
    fi

    rm -f "/run/user/$uid/yubikey-lock-screen"
  else
    logger "[yubikey] screen was not locked with yubikey"

  fi
fi
